name: .NET style check

on:
  push:
  pull_request:

jobs:
  dotnet-format:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Setup Project
      run: dotnet new classlib --langVersion 7.3
      run: rm ./Class1.cs
    - name: Add packages
      run: dotnet add package Unity3D.UnityEngine
      run: dotnet add package UnityTechnologies.UnityEditor
      run: dotnet add package StyleCop.Analyzers
      run: dotnet add package Roslynator.Analyzers
      run: dotnet add package SonarAnalyzer.CSharp
    - name: Format
      run: dotnet format --verify-no-changes --verbosity diagnostic